#!/usr/bin/env bash

echo "Creating database vaulty..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database vaulty-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://vagrant@localhost:5432/vaulty-test?sslmode=disable&password=vagrant..."
pgmgr -c ".pgmgr.test.json" db migrate
